### ISSUE TITLE
github deploy key is output in the terraform plan

### ISSUE THREAD

**Issue by ruben-cit** [dbt-labs/terraform-provider-dbtcloud#188]
Not sure what the best practise is there but feels like this probably should be marked as sensitive:

<img width="987" alt="Screenshot 2023-09-07 at 3 07 02 PM" src="https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/93541428/ef431866-83e4-47a8-a2fe-d196ae11d71f">

**Comment by b-per** [comment]
My first stance would be that as it is visible in clear text in dbt Cloud, this actually wouldn't be a sensitive value.

The `deploy_key` doesn't give you read/write access to the repo by itself. This is the value that needs to be manually added on the GitHub side to then provide read/write access from dbt Cloud to the repo.

Do you see it differently?

**Comment by will-sargent-dbtlabs** [comment]
I agree @b-per. 

In fact, if you didn't get the deploy key in the output, you would not be able to copy it to your git provider without accessing it in dbt Cloud,

That being said, if you were automatically adding that deploy key to a git provider, then marking it as sensitive is a reasonable step.

I would propose we make an option in the vars that would toggle the deploy key sensitive bool, defaulting to off, since technically it will eventually have power if installed, and org policy may need to have it redacted.
