### ISSUE TITLE
No docs for dbtCloud User

### ISSUE THREAD

**Issue by LeoTheGriff** [dbt-labs/terraform-provider-dbtcloud#228]
## Describe the bug
No docs for dbtCloud User. Implied existence in: https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/resources/user_groups, specifically line `user_id = dbtcloud_user.my_user.id`

## Error message
https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/resources/user
```
Page Not Found
This documentation page doesn't exist for version 0.2.17 of the dbtcloud provider.
```
Not in guides when searching, only data sources
<img width="344" alt="image" src="https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/9199543/d80f6a8d-01e5-4a03-9b47-1e764d85e890">

## Resource configuration
NA

## Expected behavior
Docs to exist

## Config (please complete the following information):
 - dbt Cloud provider 0.2.17

**Comment by b-per** [comment]
Thanks for raising this @LeoTheGriff 

The issue here is with the docs. I will get them updated to:

```
user_id = data.dbtcloud_user.my_user.id
```

There is no resource today for `dbtcloud_user` just a datasource to get a User ID form their email.

There is already [a feature request](https://github.com/dbt-labs/terraform-provider-dbtcloud/issues/202) to handle users, but it is not trivial as dbt Cloud doesn't create users per-se, but only invites them.

**Comment by LeoTheGriff** [comment]
Thanks Benoit, that makes sense
________________________________
