### ISSUE TITLE
Support for Global Connections

### ISSUE THREAD

**Issue by ernestoongaro** [dbt-labs/terraform-provider-dbtcloud#267]

**Comment by jaklan** [comment]
@b-per any updates on that? We want to fully adopt TF-based dbt Cloud IaC (switching from an internal solution) in the upcoming weeks, but the change in Connection management could be a blocker (in terms of both Connection creation and their reference in Environments)

**Comment by b-per** [comment]
Hi @jaklan. I am just back from leave.

We are actively working on adding support for global connections in Terraform and I'd expect that it will be released in the next few days. We are going to create a new resource `dbtcloud_global_connection` that people will be able to use to set up global connections instead of the previous project-scoped ones.
