### ISSUE TITLE
Allow to retrieve i.a. connection and environment ID by their name

### ISSUE THREAD

**Issue by jaklan** [dbt-labs/terraform-provider-dbtcloud#288]
For `dbtcloud_project` we can do:

```
// or they can use project names
// the provider will raise an error if more than one project is found with the same name
data "dbtcloud_project" "test_project" {
  name = "My project name"
}
```

https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/data-sources/project

It would be great to achieve the same for other named resources like connection or environment.

**Comment by jaklan** [comment]
@b-per yeah, also noted them, just thought to make it consistent - so to have both sources listing all the specific resources and sources returning the single one matching the name. But if we have to choose one then sure, listing and custom logic on our side would also work

**Comment by b-per** [comment]
Thanks. The datasources with an `s` are much more flexible in the end, because people can actually do more than checking duplicate names.

It can for example be used to have different Terraform projects/states and still point to resources that were created from other projects or manually (e.g. people could have a project just for RBAC/groups and could still get the list of all projects as a datasource that they could then add to specific projects)

In retrospect, I would have not created a `dbtcloud_project` but a `dbtcloud_projects`, still allowing people to filter by project name.

I will add in my backlog the creation of those new datasources.

**Comment by kpawlo7** [comment]
Hi. Can you provide an example of how to retrieve only ONE specific connection from dbtcloud_global_connections in CDKTF? I want to filter out by connection name (example: name=”dev”). Something similar to what we have in dbtcloud_projects where I have optional parameter: name_contains. If you don't have an example, could you advise how to properly approach this?

**Comment by b-per** [comment]
I am personally not using the CDKTF extensively, but I got a bit [nerd sniped](https://xkcd.com/356/) with this question 🤣 

I got the following working:

```python
from cdktf import Fn, TerraformLocal, TerraformIterator
from imports.dbtcloud.provider import DbtcloudProvider
from imports.dbtcloud.data_dbtcloud_global_connections import DataDbtcloudGlobalConnections
from imports.dbtcloud.project import Project

...
        glob_conns = DataDbtcloudGlobalConnections(
            self,
            "dbtcloud_global_connections",
            )

        listIterator = TerraformIterator.from_list(
            list=glob_conns.connections,
        )

        connection_id = TerraformLocal(
            self,
            "connection-id",
            expression=Fn.element(listIterator.for_expression_for_list('val.id if val.name == "whatever name"'),0)
        )

        new_project = Project(
            self,
            "my_new_project",
            name=f"My project {connection_id.as_string}",
        )
```

`cdktf deploy` then tells me that it would create a project with the name containining the connection ID (kind of a dummy example)

This is a simple example though and wouldn't raise an error if there is no connection with the wanted name or more than one.


Also, the reason why there is a config to filter by name in `dbtcloud_projects` and not`dbtcloud_global_connections` is because the API endpoint for projects supports a filter as an input, but not the connections one.

**Comment by kpawlo7** [comment]
Hi. Just check. It works. Although I use this connection_id with Environment resource so it needs to be: 
`Connection_id.as_number` in my case. 
But anyway. Many thanks!
